#!/usr/bin/env python3
"""
AEGIS-RV CSR Map Generator
Generates: RTL CSR decoder, C header, documentation from YAML spec
"""

import yaml
import argparse
from pathlib import Path

def load_csr_spec(spec_file):
    with open(spec_file, 'r') as f:
        return yaml.safe_load(f)

def generate_csr_decoder(csr_spec, output_file):
    """Generate Verilog CSR decoder module"""
    with open(output_file, 'w') as f:
        f.write("// AUTO-GENERATED by gen_csr_map.py — DO NOT EDIT\n")
        f.write("module rt_csr_decoder (\n")
        f.write("    input  wire [11:0] i_csr_addr,\n")
        f.write("    input  wire        i_csr_wr_en,\n")
        f.write("    input  wire [31:0] i_csr_wr_data,\n")
        f.write("    output wire [31:0] o_csr_rd_data,\n")
        f.write("    output wire        o_csr_valid\n")
        f.write(");\n\n")

        for csr in csr_spec.get('csrs', []):
            addr = csr.get('address', '0x7C0')
            name = csr.get('name', 'unknown')
            access = csr.get('access', 'RW')

            f.write(f"    // {name} ({addr})\n")
            if access == 'RW':
                f.write(f"    reg [31:0] {name}_reg = 32'd0;\n")
                f.write(f"    always @(posedge i_clk) if (i_csr_wr_en && i_csr_addr == 12'h{addr[2:]})\n")
                f.write(f"        {name}_reg <= i_csr_wr_data;\n")
                f.write(f"    wire [31:0] {name} = {name}_reg;\n\n")
            elif access == 'RO':
                f.write(f"    wire [31:0] {name}; // Module-driven\n\n")
            elif access == 'RW1C':
                f.write(f"    reg [31:0] {name}_reg = 32'd0;\n")
                f.write(f"    always @(posedge i_clk) begin\n")
                f.write(f"        if (i_csr_wr_en && i_csr_addr == 12'h{addr[2:]})\n")
                f.write(f"            {name}_reg <= {name}_reg & ~i_csr_wr_data;\n")
                f.write(f"    end\n")
                f.write(f"    wire [31:0] {name} = {name}_reg;\n\n")

        f.write("    // Read data mux\n")
        f.write("    reg [31:0] csr_rd_data_mux;\n")
        f.write("    always @* begin\n")
        f.write("        csr_rd_data_mux = 32'd0;\n")
        for csr in csr_spec.get('csrs', []):
            addr = csr.get('address', '0x7C0')
            name = csr.get('name', 'unknown')
            f.write(f"        if (i_csr_addr == 12'h{addr[2:]}) csr_rd_data_mux = {name};\n")
        f.write("    end\n")
        f.write("    assign o_csr_rd_data = csr_rd_data_mux;\n")

        f.write("    // Valid: CSR space is 0x7C0-0x7FF\n")
        f.write("    assign o_csr_valid = (i_csr_addr >= 12'h7C0) && (i_csr_addr <= 12'h7FF);\n")
        f.write("endmodule\n")

def generate_c_header(csr_spec, output_file):
    """Generate C header for firmware"""
    with open(output_file, 'w') as f:
        f.write("// AUTO-GENERATED by gen_csr_map.py — DO NOT EDIT\n")
        f.write("#ifndef AEGIS_RT_CSR_H\n")
        f.write("#define AEGIS_RT_CSR_H\n\n")

        for csr in csr_spec.get('csrs', []):
            name = csr.get('name', 'unknown')
            addr = csr.get('address', '0x7C0')
            desc = csr.get('description', '')
            f.write(f"// {name} — {desc}\n")
            f.write(f"#define CSR_{name.upper()} 0x{addr[2:]}\n\n")

        f.write("#endif // AEGIS_RT_CSR_H\n")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="AEGIS-RV CSR Map Generator")
    parser.add_argument("--spec", required=True, help="CSR specification YAML file")
    parser.add_argument("--rtl-out", help="Output RTL decoder file")
    parser.add_argument("--c-out", help="Output C header file")
    args = parser.parse_args()

    spec = load_csr_spec(args.spec)

    if args.rtl_out:
        generate_csr_decoder(spec, args.rtl_out)
        print(f"[✓] Generated RTL decoder: {args.rtl_out}")

    if args.c_out:
        generate_c_header(spec, args.c_out)
        print(f"[✓] Generated C header: {args.c_out}")
