#!/usr/bin/env python3
"""
AEGIS-RV Memory Map Generator
Generates address decoder logic from memory map specification
"""

import sys
import yaml
from pathlib import Path

def generate_decoder(spec, output_dir):
    """Generate Verilog address decoder from memory map YAML"""
    entries = spec.get('entries', [])

    verilog = []
    verilog.append("//===============================================================================")
    verilog.append("// AEGIS-RV Auto-Generated Memory Address Decoder")
    verilog.append("// Generated by gen_memory_map.py — DO NOT EDIT MANUALLY")
    verilog.append("//===============================================================================")
    verilog.append("")

    for entry in entries:
        name = entry.get('name', 'UNKNOWN')
        base = entry.get('base', 0)
        size = entry.get('size', 0)
        access = entry.get('access', 'RW')
        module = entry.get('module', name)

        end = base + size - 1
        verilog.append(f"// {name}: 0x{base:08X} - 0x{end:08X} ({size}B, {access})")
        verilog.append(f"wire is_{module.lower()} = (i_addr >= 19'h{base:05X}) && (i_addr < 19'h{(base+size):05X});")

    verilog.append("")
    verilog.append(f"// Total entries: {len(entries)}")

    output_file = Path(output_dir) / "memory_map_decoder.vh"
    output_file.write_text('\n'.join(verilog))
    print(f"[✓] Generated memory map decoder: {output_file}")

def main():
    if len(sys.argv) < 3:
        print("Usage: gen_memory_map.py <spec.yaml> <output_dir>")
        sys.exit(1)

    spec_file = sys.argv[1]
    output_dir = sys.argv[2]

    with open(spec_file) as f:
        spec = yaml.safe_load(f)

    Path(output_dir).mkdir(parents=True, exist_ok=True)
    generate_decoder(spec, output_dir)

if __name__ == "__main__":
    main()
