#!/usr/bin/env python3
"""
AEGIS-RV WCET Analysis & Timing Constraint Generator
Generates: syn/wcet_constraints.sdc (aiT-compatible)
"""

import re
import argparse
from pathlib import Path

# WCET timing contracts from CLAUDE.md §2.3
WCET_CONTRACTS = {
    'INTERRUPT_ENTRY':       {'cycles': 12, 'from': '*irq_controller*', 'to': '*pc_mux*'},
    'CONTEXT_SHADOW_SWAP':   {'cycles': 18, 'from': '*shadow_swap*',     'to': '*reg_file*'},
    'CONTEXT_FULL_SWITCH':   {'cycles': 26, 'from': '*ctx_switch*',      'to': '*pipeline*'},
    'TCLS_QUARANTINE':       {'cycles': 5,  'from': '*tcls_mismatch*',   'to': '*quarantine_mux*'},
    'PWM_KILL_ASSERT':       {'cycles': 2,  'from': '*fault_detect*',    'to': '*pwm_gate*'},
    'XDRONE_QMUL':           {'cycles': 2,  'from': '*xdrone_qmul*',     'to': '*wb_reg*'},
    'XDRONE_KALMAN':         {'cycles': 4,  'from': '*xdrone_kalman*',   'to': '*wb_reg*'},
    # Phase 2 pipeline WCET contracts
    'MUL_LATENCY':           {'cycles': 2,  'from': '*u_muldiv*',        'to': '*wb_result*'},
    'DIV_LATENCY':           {'cycles': 4,  'from': '*u_muldiv*',        'to': '*wb_result*'},
    'FPU_SINGLE_CYCLE':      {'cycles': 1,  'from': '*u_fpu*',           'to': '*wb_result*'},
    'ATOMIC_LR_SC':          {'cycles': 1,  'from': '*u_atomic*',        'to': '*wb_result*'},
    'BRANCH_RESOLVE':        {'cycles': 1,  'from': '*u_branch*',        'to': '*pc_next*'},
    'PIPELINE_STALL_LOAD':   {'cycles': 1,  'from': '*u_pipe_ctrl*',     'to': '*pipeline_state*'},
    'CSR_ACCESS':            {'cycles': 1,  'from': '*u_csr*',           'to': '*wb_result*'},
    'WATCHDOG_TIMEOUT':      {'cycles': 1,  'from': '*u_watchdog*',      'to': '*smu_fault*'},
}

def analyze_wcet(rtl_file, constraints_file, output_file):
    """Generate WCET timing constraints in SDC format"""
    clk_period_ns = 4.167  # 240 MHz

    with open(output_file, 'w') as f:
        f.write("#===============================================================================\n")
        f.write("# AEGIS-RV WCET Timing Constraints (aiT-compatible)\n")
        f.write("# Auto-generated by wcet_analyzer.py\n")
        f.write("#===============================================================================\n\n")

        # Clock definition
        f.write(f"# Clock definition\n")
        f.write(f"create_clock -name clk_rt -period {clk_period_ns:.3f} [get_ports i_clk]\n\n")

        # Input/Output delays (conservative)
        f.write(f"# Input/Output delays (conservative)\n")
        f.write(f"set_input_delay -clock clk_rt 0.5 [all_inputs]\n")
        f.write(f"set_output_delay -clock clk_rt 0.5 [all_outputs]\n\n")

        # WCET bounding paths
        f.write("# WCET bounding paths\n")
        for name, contract in WCET_CONTRACTS.items():
            max_delay = contract['cycles'] * clk_period_ns
            f.write(f"# {name}: {contract['cycles']} cycles = {max_delay:.3f} ns\n")
            f.write(f"set_max_delay {max_delay:.3f} "
                    f"-from [get_cells {contract['from']}] "
                    f"-to [get_cells {contract['to']}]\n\n")

        # False paths
        f.write("# False paths (async/safe)\n")
        f.write("set_false_path -from [get_cells *debug_halt*] -to [get_cells *pc_update*]\n")
        f.write("set_false_path -from [get_cells *smu_fault_latch*] -to [get_cells *pipeline*]\n")

    print(f"[✓] Generated WCET constraints: {output_file}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="AEGIS-RV WCET Analyzer")
    parser.add_argument("--rtl", required=True, help="RTL source file (RT core)")
    parser.add_argument("--constraints", help="Existing constraints file")
    parser.add_argument("--output", required=True, help="Output SDC file")
    args = parser.parse_args()

    analyze_wcet(args.rtl, args.constraints, args.output)
